<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Creating global meta tag' => 'Создание глобального мета тега',
    'Creating meta tag by url' => 'Создание мета тега страницы',
    'Description' => 'Описание',
    'Details of the global meta tag' => 'Детали глобального мета тега',
    'Details of the meta tag by url' => 'Детали мета тега страницы',
    'Editing global meta tag' => 'Редактирование глобального мета тега',
    'Editing meta tag by url' => 'Редактирвание мета тега страницы',
    'Global meta tags' => 'Глобальные мета теги',
    'Keywords' => 'Ключевые слова',
    'Meta tag content' => '',
    'Meta tag name' => '',
    'Meta tags by url' => 'Мета теги страниц',
    'Page url' => 'Ссылка на страницу',
    'Reset' => 'Сбросить',
    'Search' => 'Искать',
    'Title' => 'Заголовок',
];
